# Generated by Django 5.2.14 on 2026-08-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faultreport',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='faultreport',
            name='telegram_user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
