# Generated by Django 5.2.14 on 2026-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0004_faultreport_assigned_to_faultreport_assignment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
    ]
