# Generated by Django 5.2.14 on 2026-08-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_alter_faultreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], max_length=20)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ussd.faultreport')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
    ]
